parameters: {}
environment: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    functions:
      - name: hello
        main: ''
        runtime: 'go:default'
        web: 'true'
        environment: {}
        parameters: {}

