name: strategy-color
functions:
- name: hello-function
  source_dir: packages/hello
  runtime: go119
  routes:
  - path: /func1
  github:
    repo: kamalmog/sample-functions-golang-helloworld
    branch: main
    deploy_on_push: true