name: strategy-color1
functions:
- name: hello-function
  source_dir: /packages/hello
  routes:
  - path: '/func1'
  github:
    repo: kamalmog/sample-functions-golang-helloworld
    branch: master
    deploy_on_push: true