parameters: {}
environment: {}
packages:
  - name: hello
    environment: {}
    parameters: {}
    actions:
      - name: hello-function
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}        